### PR TITLE
Prepare package config and path handling for NPM release

### PR DESCRIPTION
**Pull request by camdendotlol**
# Summary

* adds a `bin` property to the `package.json` (see https://docs.npmjs.com/cli/v9/configuring-npm/package-json#bin for explanation)
* adds a section to the README explaining how to set up a local build globally using `npm link`
* switches to native `require` imports for the `json` boilerplate files, for two benefits:
    1. Paths are automatically relative to the `js` file, so there's no need for any path-related logic to import those files
    2. The JSON is parsed automatically, instead of pulling in a string and having to parse it
* adds a `processUserPath` function to calculate the absolute path of the `targetPath` and `outputPath` provided by the user
* adds a `processRelativePath` function to get absolute paths for files within the `editioncrafter` folder
* updates the version number to 1.0.0
* includes some minor formatting/linting changes, such as removing extra spaces from the ends of lines, that VS Code does automatically when I save a file
* adds a GitHub Actions workflow to publish releases to NPM (copy/pasted and slightly adjusted from [the docs](https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages#publishing-packages-to-the-npm-registry)) - I can't test this so we may end up needing to go back and fix something on the first attempt to publish

# Note

I highly recommend removing `package-lock.json` from `.gitignore`, in case a future `jsdom` release includes breaking API changes.

# About the NPM deployment workflow

The deployment workflow requires an `NPM_TOKEN` secret stored in the repository settings. I think it's linked to an NPM account, so whoever generates the token will have their name listed on the NPM page.

In order to publish a release, we'll need to create a release here on GitHub and include the `published` tag. This was just the example from the GitHub Actions docs, and we can adjust the exact mechanism of releasing if needed.

### CODE REVIEW

**Comment by NickLaiacona** [comment]
Hi Camden, this looks good. I sent you an invite to the performantsoftware npm org. Maybe we can use that to try and end-to-end test of the publishing mechanism? Also, could we start at v0.0.1 ? There's more to do before this is v1.0.0. Removing  `package-lock.json` from `.gitignore` sounds good.

**Comment by camdendotlol** [comment]
@NickLaiacona I'm getting this notice when I click Accept on the invitation page:

Screenshot 2023-04-25 at 9 19 09 AM

**Comment by NickLaiacona** [comment]
Do you have an existing npm account that you are logged into? I sent invite to your performant address.

**Comment by camdendotlol** [comment]
@NickLaiacona Ah, that would be the reason. My NPM account is `c@camdenmecklem.com`. Is it typical to create separate NPM accounts for work or do people usually stick to a single account (like on GitHub)?

**Comment by NickLaiacona** [comment]
Hmm, I'm not familiar with norms surrounding npm.js accounts. As long as the company isn't paying for your account, it seems fine to me to use your existing personal account. I've resent the invite to c@camdenmecklem.com

**Pull request merged**
